### ISSUE TITLE
Ansible aws modules not IPV6 ready

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#27800]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
All AWS modules

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul  2 2017, 22:24:59) [GCC 7.1.1 20170621]
```

##### CONFIGURATION
Nothing specifc / noteworthy

##### OS / ENVIRONMENT
Manjaro 17.04

##### SUMMARY
Almost no aws module is able to handle ipv6 (just updated to ansible 2.3.2)

I tried following modules with no luck doing anything with ipv6:
ec2 - Auto assigning rules in the subnet are ignored, have no parameter to assign an ipv6 adress
ec2_vpc_subnets: again, no way to assign ipv6 CIDRs
ec2_vpcs: "Missing" Option to enable ipv6 CIDR assignment
ec2_groups: Again, it is not possible to assign ::0/0 as incoming rule. The play aborts with cidr_ipv6 invalid property. It is even documented in the module (that this property exists).
(almost) every facts module for aws does not return any ipv6 info even when assigned via CLI or GUI
ec2_route_table: - dest: ::0/0 is ignored and not created.

##### STEPS TO REPRODUCE
Just pick yourself an aws module and try to do anything with ipv6

##### EXPECTED RESULTS
Working ipv6 assignments

##### ACTUAL RESULTS
No ipv6 assignments and module exceptions

Sorry for not adding steps and so on. But this a very generic issue and at the moment im too frustrated :(

**Comment by ansibot** [comment]
cc @dharmabumstead
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by shepdelacreme** [comment]
I'm interested in getting IPv6 support in for AWS modules as well. I ended up abandoning using these modules for building VPC infrastructure for this reason. There has been some work recently that adds support. Below is the breakdown of various modules I think need updates to fully support IPv6 in AWS (caveat: I probably missed a couple) as well as their status today.

**Modules affected:**
- ec2:
  - [ ] Status: Module is boto only currently. It will need to support options for auto-assigning IPv6 addresses at instance launch. Not sure what else.
- ec2_vpc_net:
  - [ ] Status: Module is boto only currently. Needs refactor to boto3. Needs to support AmazonProvidedIpv6CidrBlock boolean during creation for assignment of IPv6 block and association/disassociation of IPv6 blocks after creation.
- ~~ec2_vpc_net_facts~~:
  - [x] ~~Status: Merged PR - updates to boto3 and gathers ipv6 facts in #25375~~
- ec2_vpc_subnet:
  - [ ] Status: Open PR - add ipv6 support #30444 
- ~~ec2_vpc_subnet_facts~~:
  - [x] ~~Status: Merged PR - updates to boto3 and gathers ipv6 facts in #25374~~ 
- ec2_vpc_nacl:
  - [ ] Status: Module uses boto3 but needs to support Ipv6CidrBlock parameter and ICMP6 protocol numbers.
- ec2_vpc_nacl_facts:
  - [ ] Status: Open PR - add ipv6 support and other minor fixes #30581
- ec2_vpc_route_table:
  - [ ] Status: Module is boto only. Needs refactor to boto3 to support creating routes with IPv6 CIDR as the destination.
- ec2_vpc_route_table_facts:
  - [ ] Status: Module is boto only. Needs refactor to boto3.
- ~~ec2_group:~~
  - [x] ~~Status: Merged PR - updates to boto3 and allows IPv6 rules in #25340~~ 
- ~~ec2_group_facts:~~
  - [x] ~~Status: Has always been boto3 and supported return of IPv6 facts.~~
- ec2_eni:
  - [ ] Status: Module is boto only. Needs refactor to boto3 to support IPv6 address assignment/etc.
- ec2_eni_facts:
  - [ ] Status: Module is boto only but looks like it properly returns IPv6 addresses assigned to ENIs.

**New Modules needed:**
- ec2_vpc_egress_igw:
  - [ ] Status: Open PR - adds Egress Only Internet Gateway support in #23941

**Comment by ryansb** [comment]
This is now supported in ec2_vpc_subnet as well.

**Comment by performantdata** [comment]
@ryansb, why is this closed? As of 2.7, I don't see IPv6 support on `ec2_vpc_net`, one among the many modules that @shepdelacreme listed that hasn't been addressed.

**Comment by sebastien-rosset** [comment]
> @ryansb, why is this closed? As of 2.7, I don't see IPv6 support on `ec2_vpc_net`, one among the many modules that @shepdelacreme listed that hasn't been addressed.

Same question here. I have two PRs to support IPv6 (#49979 #50004) for ec2_vpc_nacl, and I was wondering if there an active maintainer for these modules?

**Comment by dnmvisser** [comment]
I was also stuck but I'm now using to bootstrap a VPC with IPv6:

```yaml
  tasks:
    - name: Ensure main VPC is available
      ec2_vpc_net:
        name: "Our dual stack VPC"
        cidr_block: 10.0.0.0/16
      register: vpcres
    
      # Workaround while ec2_vpc_net has no such functionality
    - name: Ensure VPC has Amazon provided /56
      command: aws ec2 associate-vpc-cidr-block 
        --amazon-provided-ipv6-cidr-block --vpc-id "{{ vpcres.vpc.id }}"
      when: vpcres.vpc.ipv6_cidr_block_association_set is not defined
```

Obviously this requires `pip install awscli` etc.

**Comment by ansibot** [comment]
cc @jillr @s-hertel @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/modules/cloud/amazon -> https://galaxy.ansible.com/community/aws

For further information, please see:
https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md
