### ISSUE TITLE
[tracking] Track "packet" module changes for 2.6

### ISSUE THREAD

**Issue by vielmetti** [ansible/ansible#36005]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- packet_sshkey
- packet_device

##### ANSIBLE VERSION
```
forthcoming 2.6
```

##### CONFIGURATION

Running on [Packet.net](http://docs.ansible.com/ansible/latest/guide_packet.html)

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Several changes are in PRs pending for updates to the Packet.net
cloud provider. They didn't get into 2.5, so this issue is a tracking
issue to identify and target changes and documentation updates for 2.6.

##### STEPS TO REPRODUCE

Inspect the following PRs:

* [ ] #35225 packet_device subnet size @arctiqtim 
* [ ] #27113 packet_project @t0mk 
* [ ] #23133 packet_ip_address @t0mk 
* [ ] #27843 packet_volume_attachment @t0mk 

and these issues 

* [ ] #34165 Possible bug for Packet Host Module @goldenprifti 
* [ ] #32910 packet_device and ipxe @t0mk @kristvanbesien
* [x] #35792 docs for packet.net

##### EXPECTED RESULTS

Expected the changes to get merged in 2.5

##### ACTUAL RESULTS

Missed the 2.5 window, expect a consolidated set of changes to
be merged for 2.6

Request: add a "packet" label to Github issue labels to make this easier to track, or at least use the "cloud" label consistently.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/packet/packet_device.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/packet/packet_device.py)
* [lib/ansible/modules/cloud/packet/packet_sshkey.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/packet/packet_sshkey.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @baldwinSPC
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @teebes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jasmingacic** [comment]
These 3 PRs have been merged:
#23133
#27842
#27843

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/modules/cloud/packet/packet_sshkey.py -> https://galaxy.ansible.com/community/general
* lib/ansible/modules/cloud/packet/packet_device.py -> https://galaxy.ansible.com/community/general

For further information, please see:
https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md
