### ISSUE TITLE
docker_container `published_ports`  needs more control options

### ISSUE THREAD

**Issue by kassiansun** [ansible/ansible#44668]
##### SUMMARY
Per #21091 #21093 #21094 , there're several issues with `published_ports` parameter:

- [ ] It does not accept a single port, per #21093 
- [ ] It does not accept 'all' option, per #21091, which is supported by `docker --publish-all`
- [ ] It does not accept port range, per #21094 
- [ ] ipv6 support, per #38909 

These issues need to be verified first, and future patch can be submitted to fix them all. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_container.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@kassiansun Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @cove @dusdanig @felixfontein @joshuaconner @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Distantly related: #43177

`published_ports` accepts hostnames (and not only IP addresses), but the `docker` API treats them as `0.0.0.0`. When we work on other `published_ports` things, we could also try to improve this.

**Comment by felixfontein** [comment]
The first bug (does not accept single port) is invalid (#21093); see https://github.com/ansible/ansible/issues/21093#issuecomment-427644496

**Comment by felixfontein** [comment]
The second bug (does not accept `all`, #21091) is probably also invalid for the same reason. Since the value of `ports` is not explained in the bug report, it is impossible to say whether that's the reason. Anyway, using `all` works fine in my tests.

**Comment by felixfontein** [comment]
The missing features described here will be added in #46596.
