### ISSUE TITLE
docker_container idempotent improvements for configuration comparation

### ISSUE THREAD

**Issue by kassiansun** [ansible/ansible#44669]
##### SUMMARY
There's several issues about `docker_container` idempotent now, caused by configuration comparison:
- [ ] Per #18983 , we might need to allow set an empty `log_driver`, and default it to `json-file`, to compare it with remote config.
- [ ] Per https://github.com/ansible/ansible/issues/31377#issuecomment-373465611, `restart_retries` is not correctly detected.
- [ ] Per https://github.com/ansible/ansible/issues/31377#issuecomment-386711014, `auto_remove` is not correctly detected.
- [ ] Per https://github.com/ansible/ansible/issues/31377#issuecomment-335029634, `expected_links` might not be detected correctly.
- [ ] Per #19894, `entrypoint` is not correctly detected.

All issues need verifying first, and a single patch can fix them all.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

**Comment by kassiansun** [comment]
Some guys have left a comment on #31377 and didn't paste a difference, can you supply more information?

@macwinnie @robertdebock

**Comment by ansibot** [comment]
@kassiansun Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @cove @dusdanig @felixfontein @joshuaconner @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
I cannot reproduce #19894, the fifth in your list (`entrypoint`). Reproducer:
``` .yaml
- hosts: localhost
  tasks:
  - name: Cleanup
    docker_container:
      name: ansible-test-container
      state: absent
      force_kill: yes
    changed_when: no
  - name: Change
    docker_container:
      name: ansible-test-container
      image: ubuntu:18.04
      state: present
      entrypoint: "/bin/echo test"
  - name: No change
    docker_container:
      name: ansible-test-container
      image: ubuntu:18.04
      state: present
      entrypoint: "/bin/echo test"
```
Output:
```
PLAY [localhost] ***********************************************************

TASK [Gathering Facts] *****************************************************
ok: [localhost]

TASK [Cleanup] *************************************************************
ok: [localhost]

TASK [Change] **************************************************************
changed: [localhost]

TASK [No change] ***********************************************************
ok: [localhost]

PLAY RECAP *****************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

**Comment by felixfontein** [comment]
For #18983: how about not allowing to specify `log_options` when `log_driver` is not specified? If the container hasn't been present before, we can't use `log_options` anyway, so I think it is acceptable to make this an error.

**Comment by felixfontein** [comment]
(Or at least print a warning that it is ignored.)

**Comment by felixfontein** [comment]
The problem with `restart_retries` is similar to the `log_options` one: it is only used if `restart_policy` is given:
``` .py
        if self.restart_policy:
            params['restart_policy'] = dict(Name=self.restart_policy,
                                            MaximumRetryCount=self.restart_retries)
```

**Comment by felixfontein** [comment]
`auto_remove` (and two related) are fixed in the first commit of #44808.

**Comment by felixfontein** [comment]
I cannot reproduce something with `expected_links` either. (I tried Python 3 with `docker` and Python 2 with `docker-py`, in case that matters.)

**Comment by felixfontein** [comment]
I've added code for `restart_retries` and `log_options` so that they are ignored if `restart_policy` resp. `log_driver` is not specified (and there are warnings in that case) in #44808.

So from my point of view, everything in this thread I was able to reproduce is fixed.

**Comment by Vladimir-csp** [comment]
I'm also seeing this on CentOS 7. Using docker_container with:
```
restart_policy: always
restart: no
``` 
Also some volumes and ports. Container is always restarted. Verbose output reports this:
```
diff:
  differences:
  - init:
    container: null
    parameter: false
```

**Comment by felixfontein** [comment]
@Vladimir-csp which version of Ansible are you using? It could be that you are experiencing a bug in Ansible 2.7.2 (assuming you use that one), which was reported in #49070 and has been fixed (the fix will be included in 2.7.3).

**Comment by Vladimir-csp** [comment]
yes, 2.7.2. Thanks for the info, it's probably that problem.

**Comment by felixfontein** [comment]
@davidmarkstartapp I assume you're trying to talk to me?

There is not "the" idempotence error for `docker_container`, there were many and a lot have been fixed. Have you found one which is still there? If yes, please provide details.

And yes, 2.7.9 should be mostly fixed (same as 2.7.10), at least all errors I know about, though I fixed a new one a couple of days ago (#54954).

**Comment by davidmarkstartapp** [comment]
@felixfontein ohh sorry, yes I meant you :)
These are my templates:

```yml
- name: Stop {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    state: stopped
    stop_signal: SIGTERM
  ignore_errors: yes

- name: Remove {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    state: absent
  ignore_errors: yes

- name: Run {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    restart_policy: always
    network_mode: host
    hostname: "{{ ansible_hostname }}"
    log_driver: json-file
    log_options:
      max-size: 20m
      max-file: 1
    memory: 512m
    image: "{{ image_name }}"
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Thanks for your help!

**Comment by felixfontein** [comment]
Well, that's precisely the problem I mentioned above (#54954). You need to quote the integer parameter in `log_options`:
```.yaml
    log_options:
      max-size: 20m
      max-file: "1"
```
This is fixed in #54955 (will convert to `str` automatically and warn the user if something has to be converted).

**Comment by davidmarkstartapp** [comment]
I tried to change the `max-file` to string as you mentioned and still get the same results.
Do you have an idea about the stop / remove plays, why they also have idempotent error?

**Comment by felixfontein** [comment]
What exactly are you executing that you get idempotence problems? Above you have listed some *tasks*, not *playbooks*.

**Comment by felixfontein** [comment]
If you run the version from `devel` (which will become 2.8.0), you can use `--diff` to see why `docker_container` is seeing changes.

**Comment by davidmarkstartapp** [comment]
It's just a simple role with 5 tasks which are login to private registry, pull the relevant image and then the stop / remove / run as copied above.

Also, where can I add the `--diff` when I run the `molecule test` command?

**Comment by felixfontein** [comment]
I've never used molecule. Do I assume correctly that it runs all the five tasks twice in a row, to see whether the second run has any changes?

In that case, it's not surprising at all that there are changes, because you are explicitly stopping, removing, and (re-)creating the container.

**Comment by davidmarkstartapp** [comment]
I see!
I thought it knows to overcome it. So anyway thanks for your time!
I'll just ignore it from my molecule tests

**Comment by cooperlees** [comment]
I seem to be having an idempotent issue too with `docker_container` on:
- Ansible Version: 2.8.0
- Python Version: 3.6.8

It seems we are getting the diff of:
```
"diff": {"before": {"running": true}, "after": {"running": true}}
```
It was running before the ansible run but still gets restarted.

The docker_container looks like this (I even tried comparisons to try and stop to restarting to no avail).
```
- name: start jenkins image
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    exposed_ports:
      - 8080:8080
      - 50000:50000
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home:rw
    restart: yes
    restart_policy: unless-stopped
    # Only touch this container IF it's not running
    comparisons:
      '*': ignore
```
- I on purpose have nothing pulling the possible updated `:lts` tag (we do this manually when we're ready incase of downtime)

Please let me know if any more information helps or what I am doing wrong here.

**Comment by felixfontein** [comment]
@cooperlees this is not surprising, since you explicitly ask the container to be restarted by specifying `restart: yes`. The documentation for `restart` says: "Use with started state to force a matching container to be stopped and restarted."

If you want to configure how the container restarts in case the program stops, it is enough to supply the `restart_policy` option - which you already specified. So simply dropping `restart: yes` should solve your problem :)

**Comment by cooperlees** [comment]
Thanks @felixfontein for pointing out my clowny 🤡 use of restart. I thought that enabled it. I need to read better. Thanks again!
