### ISSUE TITLE
broken unsupported AWS integration tests

### ISSUE THREAD

**Issue by s-hertel** [ansible/ansible#55775]
##### SUMMARY
There are currently 25 unsupported (meaning they don't run in CI due to duration or permissions) AWS tests. 16 of these are in various states of broken.

Enabling more of these to run in CI and making modifications to the bot so contributors/mergers are notified that they must run the tests locally might help. General test infrastructure changes should also be tested on unsupported tests when possible and perhaps some kind of validation script to run on the tests for which we don't have resources.

* [x] ec2_instance (Issues in the runme.sh - Fixed by #44387)
* [x] ecs_cluster (Issues in the runme.sh - Fixed by #57716)
* [x] aws_eks (Issues in the runme.sh - Fixed by #57326) 
      (Now there's a failure in the tests; initial unsupported region test is broken)
* [x] cloudformation_stack_set (Issues in the runme.sh - Fixed by #57326)
* [ ] ec2_launch_template (Issues in the runme.sh - Fixed by #57326; Now the tests fail due to missing dependencies in meta/main.yml)
* [x] efs (Issues in the runme.sh - Fixed by #57326)
* [ ] elb_target (Issues in the runme.sh)
* [ ] elb_target_facts (Broke in the _facts -> _info rename; rename role inside the target)
* [ ] aws_codecommit (tests never would have worked but it's a minor fix; tests use CamelCase in the results but the module returns snake_case)
* [x] aws_kms (Broken assertion, tags are being snake_cased incorrectly by the module - Fixed by #60206 and #60059 )
* [ ] aws_secret (broken conditional, but probably a minor fix)
* [ ] cloudfront_distribution (InvalidViewerCertificate error? Don't know if the module is broken or if AWS changed something.)
* [x] ec2_asg (Might just be unstable. Different errors on Python 2 and 3, could have a Python 3 bug - Fixed by #61212)
* [ ] iam_group (Broken conditional)
* [x] iam_password_policy  (Broken assertion, module might have had a bug introduced - Fixed by #60930)
* [ ] inventory_aws_rds (Unstable, bad hardcoded assertion for one of the group names, need to use a variable instead)

cc @mattclay 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Unsupported AWS integration tests

##### ANSIBLE VERSION

```
(python3.7.2) 12:23:08 [ansible]$ ansible --version
ansible 2.9.0.dev0 config file = /Users/shertel/ansible/ansible.cfg
configured module search path = ['/Users/shertel/.ansible/plugins/modules',
'/usr/share/ansible/plugins/modules'] ansible python module location =
/Users/shertel/ansible/lib/ansible executable location =
/Users/shertel/ansible/bin/ansible python version = 3.7.2 (default,
Mar 20 2019, 13:14:56) [Clang 9.0.0 (clang-900.0.39.2)]
```

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration](https://github.com/ansible/ansible/blob/devel/test/integration)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mattclay** [comment]
@s-hertel Thanks for putting this together.

I partially disagree with one part though:

> General test infrastructure changes should also be tested on unsupported tests when possible

I don't think running the unsupported tests (in general, not just for AWS) is very practical. We currently have over 200 unsupported integration tests. In addition to that, there are integration tests which should be marked unsupported, but are instead relying on the auto-skip behavior of cloud plugins in CI, effectively making them unsupported.

**Comment by s-hertel** [comment]
`when possible` was the key part of that. For AWS, I'm still happy to run the unsupported tests in my own account. If 25 turns into 100, yes, that's less practical for me to have running in the background. I think a more general validator would be helpful for unsupported tests when we/I don't have the resources. For example, a bunch of these tests are failing in the runme.sh due to recent changes. A sanity check could catch these problems for unsupported tests in general. It seems like just keeping tests functional is a lot of overhead but a bunch of these could have been avoided. But in the bigger picture, I think we need to draw attention to the fact when there are tests for modified modules that CI is not running. I think many contributors would be willing to run tests, it's just easy to make the assumption that CI is already doing it.

**Comment by markuman** [comment]
That hits my pull request: https://github.com/ansible/ansible/pull/57394

> [ ] elb_target (Issues in the runme.sh)

is already someone working on this? Or can someone guide me to what is need to do.   
ATM I'm not able to run `test/runner/ansible-test integration -v --python 3.7 elb_target --docker --allow-unsupported` after filling out `test/integration/cloud-config-aws.ini`

**Comment by tremble** [comment]
@s-hertel aws_kms issues are being addressed as a part of #60206 and #60154 by myself and @willthames

**Comment by tremble** [comment]
@s-hertel #60930 addresses iam_password_policy.  Looks like the tests never worked (from day one "changed" was hard coded to True) if you'd be so kind as to review I'd appreciate it.

**Comment by tremble** [comment]
@s-hertel ec2_asg the main issue I was hitting during testing was caused by timeouts.  Not sure if there's been other work

**Comment by tremble** [comment]
@s-hertel First three commits of #61263 fix the aws_codecommit tests I can split them off if you'd like

**Comment by tremble** [comment]
@s-hertel hopefully that's fixes for the last of the integration tests

**Comment by s-hertel** [comment]
There are still a couple open PRs, but I'm closing this since those are better places to track the individual issues. Thanks @tremble!
