### ISSUE TITLE
[8/7]Batch updates to EOL docs branches

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#71923]
We have some tidy-up tasks to do on the EOL docs (2.x - 2.7). This issue tracks those updates for:

- [x]  Edit on Github goes to devel. Since there has been a lot of change in devel, we are removing Edit on Github from all EOL branches.

- [x] stub out all the old porting guides to point to devel as that is the place developers keep them updated. (fix in 2.10 and then backport PR down to 2.3. - https://github.com/ansible/ansible/issues/71687

- [ ] Redirect a popular page on 2.4 to latest - https://github.com/ansible/ansible/issues/70877

- [x] Add EOL banner to 2.3 - https://github.com/ansible/ansible/issues/67008

- [x] Stub out release/maint page on 2.3 https://github.com/ansible/ansible/pull/71476

NOTE: The goal is to apply one PR for each branch, where that PR contains commits to fix each of the items above that are applicable to that branch.
 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs.ansible.com

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/README.md`](https://github.com/ansible/ansible/blob/devel/docs/docsite/README.md)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samccann** [comment]
After discussion, we decided not to put  the redirect in for  the 2.4 page as that would prevent anyone from ever accessing that page. We already have an EOL banner at the top with a link to /latest/ to make it obvious this is old old documentation.
