### ISSUE TITLE
Tracking issue - ansible-core 2.12 docs needs

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#75664]
### Summary

This is an issue to track the documentation needs for the ansible-core 2.12 release. This will link to other issues that have been identified as having documentation needs that have not been completed yet. If you have a documentation need for 2.12, please link to the issue so we can track it here. 

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/roadmap/ROADMAP_2_12.rst

### Ansible Version

```console
ansible 2.12
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 34

### Additional Information

This ensures we have the required documentation when the project releases.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/roadmap/ROADMAP_2_12.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_12.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samccann** [comment]
Docs needs:

- [ ] Follow the Docs release checklist for 2.12 (similar to this isssue from 2.11 - https://github.com/ansible/ansible/issues/74422)
- [ ] backport docs-only PRs to stable-2.12 branch on a weekly basis until release.
- [ ] docs for ansible-test split controller - https://github.com/ansible/ansible/pull/75605#issuecomment-915776089
- [ ] docs pipeline updates for new plugin attributes support https://github.com/ansible/ansible/issues/75164 
- [ ] ssh pr - https://github.com/ansible/ansible/pull/73708 breaks ssh plugin docs. Should the code PR be reverted? (@nitzmahone ??)
- [ ] side-car docs (expand ansible-doc coverage PR https://github.com/ansible/ansible/pull/74963 if it is merged for 2.12)

Items not included in core-2.12 (listing here in case that changes)
- [ ] allow argspec modifiers to be part of docstring - https://github.com/ansible/ansible/pull/74873 (most likely not coming for 2.12)
- [ ] semantic markup for plugin docs (https://github.com/ansible/ansible/pull/74937 and https://github.com/ansible-community/antsibull/pull/281)

**Comment by samccann** [comment]
Detailed release checklists at  https://github.com/ansible/ansible/issues/75884 and https://github.com/ansible/ansible/issues/75884
