### ISSUE TITLE
Documentation release checklist for Ansible 5

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#75884]
### Summary

docs release checklist for Ansible 5 release. See comment for list of actions.

### Issue Type

Documentation Report

### Component Name

docs/docsite/sphinx_conf/ansible_conf.py

### Ansible Version

```console
$ ansible --version
4
```

### Configuration

```console
$ ansible-config dump --only-changed
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/sphinx_conf/ansible_conf.py`](https://github.com/ansible/ansible/blob/devel/docs/docsite/sphinx_conf/ansible_conf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samccann** [comment]
Update the documentation and publish the 5 version of Ansible documentation. Tasks include:

Pre-release tasks:
- [ ] Update the Release Status grid on the Release and Maintenance page in devel to link in changelogs and mark Ansible 4 as EOL, and add Ansible 6 as in development.
- [ ] Verify that the Ansible 5 porting guide has a link to the Ansible 5 changelog file in gitub.
- [ ] Add a skeleton Ansible roadmap file for 6 to the `devel` branch if not already present.
- [ ]  Verify or add Ansible 6 roadmap to the exclude_patterns in core_conf.py 
- [ ] Verify that Ansible 5 roadmap and porting guide are in the exclude_patterns in core_conf.py in devel and stable-2.12
- [ ] Verify that release/main page and roadmap pages only exist in devel
- [ ] Make sure all server-side redirects are updated as necessary - see https://github.com/ansible/docsite/pull/11 and https://github.com/ansible/docsite/pull/47
- [ ] update ansible_conf.py:
  - [ ] Set 'latest_version': '5 ', under html_context
  - [ ] Verify core porting guide and roadmaps are listed under ‘exclude_patterns’. 
  - [ ] Merge to `devel`
  - [ ] Backport to `stable-2.12`
  - [ ] In `stable-2.12` - change VERSION (capitalized) from `devel` to `5`.
- [ ] Update  the build and docsite (internal RH tasks): 
  - [ ] Update the Build_Ansible_Package_Docs publication jenkins job -Configure and add an option for the new release number to the choices available for PACKAGE_VERSION. 
  - [ ] Update the 2.9 <--> 5 redirects on the docsite repo by copying an existing .htaccess file in a release subdirectory to a new subdirectory (for example, mkdir ansible/5/ && cp ansible/4/.htaccess ansible/5/.htaccess)
- [ ] Publish 5 on release day.

Post release:
- [ ]  update intersphinx links.  see #74246 - do we need any changes to this given we have two docsites now???
- [ ] EOL Ansible 4 docs - remove version switcher and add EOL banner (see how we did this for Ansible 2.10??)
- [ ] Swiftype updates:
  - [ ]  update sitemap - see https://github.com/ansible/docsite/pull/17
  - [ ] Update Swiftype Search engine for ansibl to blacklist the EOL release (e.g. /ansible/2.10/ and /ansible/5/) 
  - [ ] Kick off a reindex on the swiftype engine

**Comment by samccann** [comment]
Based on https://github.com/ansible-community/community-topics/issues/32, is seems the new collections are:

- cisco.ise
- community.dns
- comunity.ciscosmb
- infoblox.nios_modules
- netapp.storagegrid
- cloud.common

**Comment by captn3m0** [comment]
We were updating the [endoflife.date page for Ansible](https://endoflife.date/ansible) (PR: https://github.com/endoflife-date/endoflife.date/pull/621) and were confused whether Ansible 4 is EoL or not.

The [4.0 roadmap](https://docs.ansible.com/ansible/latest/roadmap/COLLECTIONS_4.html) says:

>Minor releases will stop when Ansible-5 is released.

However, the [new release page](https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-community-changelogs) says:

>End of life after 4.10

Our [current understanding](https://endoflife.date/ansible) says:

>Maintenance fixes are guaranteed for only the latest major release.

I understand that policy adherence is best-effort, and things can change from release to release. Can you confirm that the upcoming 4.10 will be a supported release? What exactly does supported mean in this context - will there be security/maintenance patch releases on 4.10 and if yes, for how long? ("EoL after 4.10" doesn't clarify much)

Aside: [Ansible having multiple pages for release policies that are versioned](https://github.com/endoflife-date/endoflife.date/pull/547/files#diff-ecdb87a20292316e8ccadbeffbb7bf2fd3325b92225f0f873ccd3aea0f3c9eeaR68-R76) only makes it harder for users to access this information. Looking at the release PRs, it looks like this also makes it difficult for maintainers to document new releases. Maybe there should be a single canonical page in the docs instead?

**Comment by samccann** [comment]
Hi @captn3m0 !  so my understanding is that Ansible 4.10 is a coming release since Ansible 5 was such a big change (python requirement changing to 3.8 for example) that the community felt one more Ansible 4.x release was necessary this time around. As for whether 4.10.1, 4.10.2 etc will exist, I'm frankly not sure but I'll ask on the community IRC/matrix channel , then come back here to update...

As for a separate page/repo where you are gathering all the EOL data for various releases, I kind of love it, and also :cry: a bit  that it's necessary and that Ansible is adding to the confusion. I'll try to think of better ways of handling this but thanks for providing that for folks to track packages with!

**Comment by samccann** [comment]
@captn3m0 I got a bit more info - yes 4.10 is coming out to pick up some bits and bobs but is then immediately EOL.

**Comment by captn3m0** [comment]
Thanks for the confirmation 👍🏽

**Comment by samccann** [comment]
Moved Ansible 4 EOL tasks to separate issue since that is not happening simultaneous with Ansible 5 release - See https://github.com/ansible/ansible/issues/76495
