### ISSUE TITLE
Documentation Checklist - ansible-core 2.12 release

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#75883]
### Summary

Documentation checklist to prepare for and deliver the ansible-core 2.12 release. See followon comment for the full checklist.

### Issue Type

Documentation Report

### Component Name

docs/docsite/sphinx_conf/ansible_conf.py

### Ansible Version

```console
2.12
```

### Configuration

```console
$ ansible-config dump --only-changed
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/sphinx_conf/ansible_conf.py`](https://github.com/ansible/ansible/blob/devel/docs/docsite/sphinx_conf/ansible_conf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samccann** [comment]
Tasks include:

- [ ] remove the release/maintenance page and porting guide pages from the new release when the branch is created and replace with stub page pointing up to the devel versions of these release-independent pages.
- [ ] Review changelogs in stable-2.12 for ansible-core
- [ ] Review ansible-core porting guide and ensure it links to core 2.12 changelogs
- [ ] include ansible-core in Release Status Grid and ensure maintenance/eol releases listed accurately. Include links to changelogs.
- [ ] Add skeleton roadmap for 2.13-core
- [ ] Add skeleton porting guide for 2.13-core
- [ ] Update core_conf.py:
    - [ ] Update copyright to current year, if not already updated.
    - [ ] Set 'latest_version': '2.12 ', under html_context
    - [ ] Update ‘available_versions’ to 2.12, 2.11, devel, under ‘html_context’.
    - [ ] Verify Ansible package porting guide and roadmaps are listed under ‘exclude_patterns’. 
    - [ ] Merge to `devel`
    - [ ] Backport to `stable-2.12`
    - [ ] In `stable-2.12` - change VERSION (capitalized) from `devel` to `2.12`.
- [ ] publish on release day.

Post release:
- [ ]  update intersphinx links.  see #74246  (do we have to do anything special since this is ansible-core docsite and not Ansible???)
- [ ] Update the “too old” version number that suppresses the publication of “version_added” metadata older than a certain Ansible version, see https://github.com/ansible/ansible/pull/50097 (does this still exist??)
- [ ] Update the backport instructions to target the new “latest” branch, see https://github.com/ansible/ansible/pull/56578 
- [ ] Make sure all server-side redirects are updated as necessary - see https://github.com/ansible/docsite/pull/11 
- [ ] End-of-life the 2.10 docs
   - [ ] In the EOL branch (stable-2.10), update page banner to EOL to the release no longer supported. See https://github.com/ansible/ansible/pull/64118
  - [ ] In the EOL branch (stable-2.10), remove ansible_version.hml from layout.html in the theme.
- [ ] Swiftype updates
  - [ ] Update Swiftype Search engine for ansible-core to blacklist the EOL release (e.g. /ansible/2.10/) 
  - [ ] Kick off a reindex on the swiftype engine

**Comment by samccann** [comment]
Released and published.
