### ISSUE TITLE
Documentation Checklist - ansible-core 2.13 release

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#77574]
### Summary

Documentation checklist to prepare for and deliver the ansible-core 2.13 release. See follow-on comment for the full checklist.

### Issue Type

Documentation Report

### Component Name

docs/docsite/sphinx_conf/core_conf.py

### Ansible Version

```console
$ ansible --version
2.13
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

n/a

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/sphinx_conf/core_conf.py`](https://github.com/ansible/ansible/blob/devel/docs/docsite/sphinx_conf/core_conf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samccann** [comment]
Tasks include:

- [ ] remove the release/maintenance page and porting guide pages from the new release when the branch is created and replace with stub page pointing up to the devel versions of these release-independent pages.
- [ ] Review changelogs in stable-2.13 for ansible-core
- [ ] Review ansible-core porting guide and ensure it links to core 2.13 changelogs
- [ ] include ansible-core in Release Status Grid and ensure maintenance/eol releases listed accurately. Include links to changelogs.
- [ ] Update core_conf.py:
    - [ ] Set 'latest_version': '2.13 ', under html_context
    - [ ] Update ‘available_versions’ to latest, 2.12, 2.11,  devel, under ‘html_context’.
    - [ ] Merge to `devel`
    - [ ] Backport to `stable-2.13`, `stable-2.12`, and `stable-2.11`
    - [ ] Verify Ansible package porting guide and roadmaps are listed under ‘exclude_patterns’. 
    - [ ] In `stable-2.13` - change VERSION (capitalized) from `devel` to `2.13`.

- [ ] publish on release day.
- [ ] Translation docs for core:
    - [ ] test publish core-2.13 with japanese language selection in Jenkins job. If successful, publish to prod.
    - [ ] Update the docsite to include the new translation - see https://github.com/ansible/docsite/pull/77

Post release:
- [ ] Update the backport instructions to target the new “latest” branch, see https://github.com/ansible/ansible/pull/56578 
- [ ] Make sure all server-side redirects are updated as necessary - see https://github.com/ansible/docsite/pull/11 
- [ ] Swiftype updates
  - [ ] Update Swiftype Search engine for ansible-core to blacklist the EOL release (e.g. /ansible/2.9/  and ansible/2.10/) -
  - [ ] Kick off a reindex on the swiftype engine
- [ ] End-of-life the 2.9 docs
   - [ ] In the EOL branch (stable-2.9), update page banner to EOL to the release no longer supported. Point to core docs for RH customers. See https://github.com/ansible/ansible/pull/64118
  - [ ] In the EOL branch (stable-2.9), remove ansible_version.hml from layout.html in the theme.
 
- [ ] End-of-life the 2.10 docs
   - [ ] In the EOL branch (stable-2.10), update page banner to EOL to the release no longer supported. See https://github.com/ansible/ansible/pull/64118
  - [ ] In the EOL branch (stable-2.10), remove ansible_version.hml from layout.html in the theme.
