### ISSUE TITLE
Documentation release checklist for Ansible 6

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#77575]
### Summary

docs release checklist for Ansible 5 release. See comment for list of actions.

### Issue Type

Documentation Report

### Component Name

docs/docsite/sphinx_conf/ansible_conf.py

### Ansible Version

```console
$ ansible --version
2.13
```

### Configuration

```console
$ ansible-config dump --only-changed
n/a
```

### OS / Environment

n/a

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Update the documentation and publish the 5 version of Ansible documentation. Tasks include:

Pre-release tasks:
- [ ] Update the Release Status grid on the Release and Maintenance page in devel to link in changelogs and mark Ansible 4 as EOL, and add Ansible 6 as in development.
- [ ] backport to stable-2.13
- [ ] Verify that the Ansible 5 porting guide has a link to the Ansible 6 changelog file in gitub.
- [ ] Build docs and validate new collections docs after they are added to https://github.com/ansible-community/ansible-build-data
- [ ]  Verify or add Ansible 6 roadmap to the exclude_patterns in core_conf.py 
- [ ] Verify that Ansible 6 roadmap and porting guide are in the exclude_patterns in core_conf.py in devel and stable-2.13
- [ ] Verify that release/main page and porting pages are kept in sync between latest and devel
- [ ] Make sure all server-side redirects are updated as necessary - see https://github.com/ansible/docsite/pull/11 and https://github.com/ansible/docsite/pull/47
- [ ] update ansible_conf.py:
  - [ ] Set 'latest_version': '6 ', under html_context
  - [ ] Verify core porting guide and roadmaps are listed under ‘exclude_patterns’. 
  - [ ] Merge to `devel`
  - [ ] Backport to `stable-2.13`
  - [ ] In `stable-2.13` - change VERSION (capitalized) from `devel` to `6`.
- [ ] Update  the build and docsite (internal RH tasks): 
  - [ ] Update the Build_Ansible_Package_Docs publication jenkins job -Configure and add an option for the new release number to the choices available for PACKAGE_VERSION. 
- [ ] Publish 6 on release day. Then immediately:
  - [ ] Update the 2.9 <--> 6 redirects on the docsite repo by copying an existing .htaccess file in a release subdirectory to a new subdirectory (for example, mkdir ansible/6/ && cp ansible/5/.htaccess ansible/6/.htaccess) and republish the docsite. - do we need to keep doing this after this release?

Post release:
- [ ]  update intersphinx links.  see #74246 - do we need any changes to this given we have two docsites now???
  - [ ] backport to stable-2.13 and republish
- [ ] EOL Ansible 5 docs - remove version switcher and add EOL banner (see how we did this for Ansible 4??) after some final Ansible 5.x release??
- [ ] Swiftype updates:
  - [ ]  update sitemaps for Ansible and ansible-controller - see https://github.com/ansible/docsite/pull/69
  - [ ] Update Swiftype Search engine for ansible to blacklist the EOL release (e.g. /ansible/2.10/ 2.9, and /ansible/5/) 
  - [ ] Kick off a reindex on the swiftype engine

**Comment by samccann** [comment]
- [ ] Review https://github.com/ansible/ansible/issues/75884#issuecomment-985979767 to see what we can do better this time to make EOL information clearer.

**Comment by samccann** [comment]
- [ ] test and publish docsite redirects PR to handle move getting started guide. - https://github.com/ansible/docsite/pull/93

**Comment by samccann** [comment]
From 'Added Collections` in the ansible 6 changelogs, we have the following new collections:

- [ ] cisco.dnac
- [ ] community.sap_libs
- [ ] vmware.vmware_rest
- [ ] community.sap

**Comment by samccann** [comment]
vmware.vmware_rest has some odd short description problem showing up on a few modules:
![image](https://user-images.githubusercontent.com/30267855/173418332-7bd6bb0f-fd2a-4e54-9b71-1ae3e77b229c.png)

Opened an issue in that repo to investigate - https://github.com/ansible-collections/vmware.vmware_rest/issues/337

**Comment by samccann** [comment]
@sugitk The docsite is still there so any urls you have should still work. It's just that we don't have it in the version dropdown anymore.
But in case it's not clear to anyone else finding this issue, the 2.9 docs remain at https://docs.ansible.com/ansible/2.9/index.html for the foreseeable future.

**Comment by samccann** [comment]
After review, the decision is we need to keep 2.9 in the version-switcher until it EOLs for RH customers as well since there is no easy solution for those folks to find the docs. The EOL banner will remain, but  the 2.9 will also remain an option in the version switcher for now.
