### ISSUE TITLE
Documentation Checklist: -ansible-core 2.14 release

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#78880]
### Summary

Documentation checklist to prepare for and deliver the ansible-core 2.14 release. See follow-on comment for the full checklist.

### Issue Type

Documentation Report

### Component Name

docs/docsite/sphinx_conf/ansible_conf.py

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
Tasks include:

- [ ] Review changelogs in stable-2.14 for ansible-core
- [ ] Review ansible-core porting guide and ensure it links to core 2.14 changelogs
- [ ] include ansible-core in Release Status Grid and ensure maintenance/eol releases listed accurately. Include links to changelogs.
- [ ] Update core_conf.py:
    - [ ] Set 'latest_version': '2.14 ', under html_context
    - [ ] Update ‘available_versions’ to 2.14, 2.13, 2.12,  devel, under ‘html_context’.
    - [ ] Merge to `devel`
    - [ ] Backport to `stable-2.14`, `stable-2.13`, and `stable-2.12`
    - [ ] Verify Ansible package porting guide and roadmaps are listed under ‘exclude_patterns’. 
    - [ ] In `stable-2.14` branch - change VERSION (capitalized) from `devel` to `2.14`.

- [ ] publish on release day.
- [ ] Translation docs for core (this usually lags some time so may need to open separate issue to track):
    - [ ] test publish core-2.14 with japanese language selection in Jenkins job. 
    - [ ] Update `core_lang_conf.py:
       - [ ]  - Ensure `exclude patterns' match core_conf.py
       - [ ]  Set 'latest_version': '2.14 ', under html_context
      - [ ] Update ‘available_versions’ to 2.14, 2.13, 2.12,  devel, under ‘html_context’.
      - [ ] Merge to `devel`
      - [ ] Backport to `stable-2.14`, `stable-2.13`, and `stable-2.12`
    - [ ] publish to prod.
    - [ ] Update the docsite to include the new translation - see https://github.com/ansible/docsite/pull/77

Post release:
- [ ] Update the backport instructions to target the new “latest” branch, see https://github.com/ansible/ansible/pull/56578 
- [ ] Make sure all server-side redirects are updated as necessary - see https://github.com/ansible/docsite/pull/11 
- [ ] Swiftype updates
  - [ ] Update Swiftype Search engine for ansible-core to blacklist the EOL release (e.g. /ansible/2.9/  and ansible/2.10/) -
  - [ ] Kick off a reindex on the swiftype engine
- [ ] End-of-life the 2.11 docs
   - [ ] In the EOL branch (stable-2.11), update page banner to EOL to the release no longer supported. See https://github.com/ansible/ansible/pull/76669/files
  - [ ] In the EOL branch (stable-2.11), remove ansible_version.hml from layout.html in the theme.

**Comment by Dule-martins** [comment]
Hello, @samccann Do I have to create a new file for this or is there an existing file that I have to include this to?

**Comment by Dule-martins** [comment]
Ok then, take your time in getting the writeup in place.

**Comment by samccann** [comment]
Hi @Dule-martins - do you have time to do the PR reviews for the PRs listed above? They are all in draft state until we release, but I could do with PR reviews by Friday if possible.

Feel free to ask questions in each PR because a lot of them have to do with how the Sphinx build works in Ansible.

@oraNod - would also like your reviews as well.. thanks!

**Comment by Dule-martins** [comment]
Ok, let me give it a check
