### ISSUE TITLE
Documentation Release checklist for Ansible 7

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#79378]
### Summary

Release checklist for Ansible 7 documentation. See followon comment for full list.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/index.rst

### Ansible Version

```console
$ ansible --version
2.14
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/api/index.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/api/index.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samccann** [comment]
Update the documentation and publish the 7 version of Ansible documentation. Tasks include:

Pre-release tasks:

- [ ] Stage the release docs on test when RC is available.
- [ ] Update the Release Status grid on the Release and Maintenance page in devel to link in changelogs and mark Ansible 6 as EO after 6.7, and add Ansible 8 as in development.
- [ ] backport to stable-2.14
- [ ] Verify that the Ansible 7 porting guide has a link to the Ansible 7 changelog file in gitub.
- [ ] Build docs and validate new collections docs after they are added to https://github.com/ansible-community/ansible-build-data
- [ ]  Verify or add Ansible 7 roadmap to the exclude_patterns in core_conf.py 
- [ ] Verify that Ansible 7 roadmap and porting guide are in the exclude_patterns in core_conf.py in devel and stable-2.14
- [ ] Verify that release/main page and porting pages are kept in sync between latest and devel
- [ ] Make sure all server-side redirects are updated as necessary - see [https://github.com/ansible/docsite/pull/11 and https://github.com/ansible/docsite/pull/47](https://github.com/ansible/docsite/pull/110) 
- [ ] update ansible_conf.py:
  - [ ] Set 'latest_version': '7 ', under html_context
  - [ ] Verify core porting guide and roadmaps are listed under ‘exclude_patterns’. 
  - [ ] Merge to `devel` on **release day only**
  - [ ] Backport to `stable-2.14`
  - [ ] In `stable-2.14` - change VERSION (capitalized) from `devel` to `7`.
- [ ] Update  the build and docsite (internal RH tasks): 
  - [ ] Update the Build_Ansible_Package_Docs publication jenkins job -Configure and add an option for the next release number to the choices available for PACKAGE_VERSION. (aka add 8).
- [ ] Publish 7 on release day. Then immediately:
  - [ ] Update the 2.9 <--> 7 redirects on the docsite repo by copying an existing .htaccess file in a release subdirectory to a new subdirectory (for example, mkdir ansible/7/ && cp ansible/6/.htaccess ansible/7/.htaccess) and republish the docsite. - do we need to keep doing this now since 2.9 is EOL thus not on version switcher?

Post release:
- [ ]  update intersphinx links.  see #74246 - do we need any changes to this given we have two docsites now???
  - [ ] backport to stable-2.14 and republish
- [ ] EOL Ansible 6 docs -  set `is_eol` to `True` in `html_context` to remove version switcher and add EOL banner after  final Ansible 6.7.0 release. See https://github.com/ansible/ansible/pull/78127
- [ ] Swiftype updates:
  - [ ]  update sitemaps for Ansible and ansible-controller - see https://github.com/ansible/docsite/pull/69
  - [ ] Update Swiftype Search engine for ansible to blacklist the EOL release (e.g. /ansible/6/) 
  - [ ] Kick off a reindex on the swiftype engine
